language: node_js

node_js:
  - 10

before_deploy:
  - git remote remove origin
  - git remote add origin https://${GH_TOKEN}@github.com/${GH_USERNAME}/wizeline/lerna-leo.git
  - git reset --hard master
  - git checkout master
jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run publish
