---
name: Node.js CI

on:               
  pull_request:                    
    branches:
      - 'master'                 

jobs:
  build:
    runs-on: ${{ matrix.os }}          
    
    strategy:                          
      matrix:
        node: [12.x]
        os: [ubuntu-latest]

    steps:
    - name: Checks-out repository
      uses: actions/checkout@v2
    - name: Use NodeJS ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: CI process
      run: npm ci
    - name: Building script
      run: npm run build --if-present
    - name: Test process
      run: npm test
      env:
        CI: true
...