name: CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checks-out repository
        uses: actions/checkout@v2

      - name: checkout
        uses: actions/checkout@v1

      - name: Configure CI Git User
        run: |
          git config --global user.name 'MartinRoman94'
          git config --global user.email 'martin.arcos@wizeline.com'
          git remote set-url origin https://$GITHUB_ACTOR:$GH_TOKEN@github.com/wizeline/lerna-leo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Checkout and pull branch
        run: git checkout "${GITHUB_REF:11}" && git pull

      - name: Install Packages
        run: |
          pwd
          ls -la
          for d in packages/access-decision-manager-express/examples/* ; do (cd "$d" && npm i); done
          npm ci

      - name: Authenticate with Registry
        run: |
          echo "registry=http://registry.npmjs.org/" > .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Publish package
        run: npm run publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
