# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:                             # Detect push event
    branches-ignore: [ master ]     # Ignore push in master branch 
  pull_request:                     # Detect pull requests events
    branches: [ master ]            # Over branch master

jobs:
  build:

    runs-on: ${{ matrix.os }}          # Enviroment of deploy to test
    
    strategy:                          # Run job with different versions of Node.js and Ubuntu
      matrix:                   
        node: [10.x, 12.x]
        os: [ubuntu-16.04, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
