# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

---
name: Node.js CI

on:
  push:                             # Detect push event
    branches-ignore: 
      - 'master'                  # Ignore push in master branch 
  pull_request:                     # Detect pull requests events
    branches:
      - 'master'                  # PRs over branch master

jobs:
  build:

    runs-on: ${{ matrix.os }}          # Enviroment of deploy to test
    
    strategy:                          # Run job with different versions of Node.js and Ubuntu
      matrix:                   
        node: [10.x, 12.x]
        os: [ubuntu-16.04, ubuntu-18.04]

    steps:
    - name: Checks-out repository
      uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-    
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: CI process
      run: npm ci
    - name: Building script
      run: npm run build --if-present
    - name: Test process
      run: npm test
      env:
        CI: true
...