---
name: Node.js Publish

on:
  push:
    branches:
      - master
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:                          
      matrix:              
        node: [12.x]
        os: [ubuntu-latest]
    
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v2
      - name: Use NodeJS ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'
      - name: link
        run: cat ~/.npmrc
        run: npm run link
      - name: CI process
        run: for d in packages/access-decision-manager-express/examples/* ; do (cd "$d" && npm i); done 
        run: npm ci
      - name: Build process
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
...