---
name: CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checks-out repository
        uses: actions/checkout@v2

      - name: checkout
        uses: actions/checkout@v1

      - name: Configure CI Git User
        run: |
          git config --global user.name 'MartinRoman94'
          git config --global user.email 'martin.arcos@wizeline.com'
          git remote set-url origin https://${GH_TOKEN}@github.com/wizeline/lerna-leo1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USER: ${{ secrets.GH_USER }}

      - name: Checkout to master
        run: git checkout master

      - name: Authenticate with Registry
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      
      - name: Install Packages
        run: |
          npm ci

      - name: Publish package
        run: npm run publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
...