---
name: CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checks-out repository
        uses: actions/checkout@v2

      - name: checkout
        uses: actions/checkout@v1

      - name: Configure CI Git User
        run: |
          git config --global user.name 'LeoUrzua'
          git config --global user.email 'd.leonardo.urzua@gmail.com'
          git remote set-url origin https://LeoUrzua:$GH_TOKEN@github.com/wizeline/lerna-leo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Checkout and pull branch
        run: git checkout master

      - name: Authenticate with Registry
        run: |
          echo "registry=http://registry.npmjs.org/" > .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      
      - name: Install Packages
        run: |
          npm ci

      - name: Publish package
        run: npm run publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
...