---
name: Node.js Publish

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  publish:
    name: Publish
    runs-on: ${{ matrix.os }}          
    
    strategy:                          
      matrix:
        node: [12.x]
        os: [ubuntu-latest]

    steps:
      - name: Checks-out repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node }}
          persist-credentials: false
      - name: Git identity
        run: |
          git config --global user.name 'MartinRoman94'
          git config --global user.email 'martin.arcos@wizeline.com'
          git remote set-url origin https://MartinRoman94:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Authenticate in registry
        run: |
          echo "registry=http://registry.npmjs.org/" > .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Checkout to master
        run: git checkout master
      - name: Install dependencies
        run: npm ci
      - name : Link packages
        run: npm run link
      - name: Publish
        run: npm run publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
...